project_directory: project
external_projects: []
ignore_paths:
  - features/project
console_port: 4242
project_key: kbs

# Hierarchy and types are fixed today; kept here for validation.
hierarchy:
  - initiative
  - epic
  - task
  - sub-task
types:
  - bug
  - story
  - chore

workflows:
  default:
    backlog: [open, closed]
    open: [in_progress, closed, deferred]
    in_progress: [open, blocked, closed]
    blocked: [in_progress, closed]
    closed: [open]
  epic:
    open: [in_progress, closed]
    in_progress: [open, closed]
    closed: [open]

# Status colors (per workflow states)
status_colors:
  backlog: yellow

  open: cyan
  in_progress: blue
  blocked: red
  closed: green

initial_status: open
priorities:
  0:
    name: critical
    color: red
  1:
    name: high
    color: bright_red
  2:
    name: medium
    color: yellow
  3:
    name: low
    color: blue
  4:
    name: trivial
    color: white
default_priority: 2

type_colors:
  initiative: bright_blue
  epic: magenta
  task: blue
  sub-task: bright_cyan
  bug: red
  story: yellow
  chore: green
  event: bright_blue

beads_compatibility: true
